///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace mobile1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the mobile1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("7cdff45d-e861-44d6-8242-ffbcdb6e1e3f")]
    public partial class mobile1Repository : RepoGenBaseFolder
    {
        static mobile1Repository instance = new mobile1Repository();
        mobile1RepositoryFolders.BrowserAppFolder _browser;
        mobile1RepositoryFolders.ComPruebaMaverickAppFolder _compruebamaverick;

        /// <summary>
        /// Gets the singleton class instance representing the mobile1Repository element repository.
        /// </summary>
        [RepositoryFolder("7cdff45d-e861-44d6-8242-ffbcdb6e1e3f")]
        public static mobile1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public mobile1Repository() 
            : base("mobile1Repository", "/", null, 0, false, "7cdff45d-e861-44d6-8242-ffbcdb6e1e3f", ".\\RepositoryImages\\mobile1Repository7cdff45d.rximgres")
        {
            _browser = new mobile1RepositoryFolders.BrowserAppFolder(this);
            _compruebamaverick = new mobile1RepositoryFolders.ComPruebaMaverickAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7cdff45d-e861-44d6-8242-ffbcdb6e1e3f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Browser folder.
        /// </summary>
        [RepositoryFolder("d8914c51-2151-4bff-bb4c-050a745e84a1")]
        public virtual mobile1RepositoryFolders.BrowserAppFolder Browser
        {
            get { return _browser; }
        }

        /// <summary>
        /// The ComPruebaMaverick folder.
        /// </summary>
        [RepositoryFolder("859bd624-5d3a-4d52-873a-fbb16dc77212")]
        public virtual mobile1RepositoryFolders.ComPruebaMaverickAppFolder ComPruebaMaverick
        {
            get { return _compruebamaverick; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class mobile1RepositoryFolders
    {
        /// <summary>
        /// The BrowserAppFolder folder.
        /// </summary>
        [RepositoryFolder("d8914c51-2151-4bff-bb4c-050a745e84a1")]
        public partial class BrowserAppFolder : RepoGenBaseFolder
        {
            mobile1RepositoryFolders.DomAppFolder _dom;
            RepoItemInfo _eturlInfo;
            RepoItemInfo _rxbrowseractivityInfo;

            /// <summary>
            /// Creates a new Browser  folder.
            /// </summary>
            public BrowserAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Browser", "/mobileapp[@title='ranorex.RxBrowser']", parentFolder, 10000, null, false, "d8914c51-2151-4bff-bb4c-050a745e84a1", "")
            {
                _dom = new mobile1RepositoryFolders.DomAppFolder(this);
                _eturlInfo = new RepoItemInfo(this, "EtUrl", "form[@title='RxBrowserActivity']//container[@rid='UrlHeader']/text[@accessibilityid='Url']", 30000, null, "f18de854-371a-48eb-97d3-1cfeed19cf6c");
                _rxbrowseractivityInfo = new RepoItemInfo(this, "RxBrowserActivity", "form[@title='RxBrowserActivity']", 30000, null, "85e14f5f-b24b-4850-ba75-0ced64e3da89");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d8914c51-2151-4bff-bb4c-050a745e84a1")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d8914c51-2151-4bff-bb4c-050a745e84a1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EtUrl item.
            /// </summary>
            [RepositoryItem("f18de854-371a-48eb-97d3-1cfeed19cf6c")]
            public virtual Ranorex.Text EtUrl
            {
                get
                {
                    return _eturlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EtUrl item info.
            /// </summary>
            [RepositoryItemInfo("f18de854-371a-48eb-97d3-1cfeed19cf6c")]
            public virtual RepoItemInfo EtUrlInfo
            {
                get
                {
                    return _eturlInfo;
                }
            }

            /// <summary>
            /// The RxBrowserActivity item.
            /// </summary>
            [RepositoryItem("85e14f5f-b24b-4850-ba75-0ced64e3da89")]
            public virtual Ranorex.Form RxBrowserActivity
            {
                get
                {
                    return _rxbrowseractivityInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The RxBrowserActivity item info.
            /// </summary>
            [RepositoryItemInfo("85e14f5f-b24b-4850-ba75-0ced64e3da89")]
            public virtual RepoItemInfo RxBrowserActivityInfo
            {
                get
                {
                    return _rxbrowseractivityInfo;
                }
            }

            /// <summary>
            /// The Dom folder.
            /// </summary>
            [RepositoryFolder("34e257fc-747c-449b-a245-956db607a438")]
            public virtual mobile1RepositoryFolders.DomAppFolder Dom
            {
                get { return _dom; }
            }
        }

        /// <summary>
        /// The DomAppFolder folder.
        /// </summary>
        [RepositoryFolder("34e257fc-747c-449b-a245-956db607a438")]
        public partial class DomAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dom  folder.
            /// </summary>
            public DomAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dom", ".//dom", parentFolder, 10000, null, false, "34e257fc-747c-449b-a245-956db607a438", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("34e257fc-747c-449b-a245-956db607a438")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("34e257fc-747c-449b-a245-956db607a438")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ComPruebaMaverickAppFolder folder.
        /// </summary>
        [RepositoryFolder("859bd624-5d3a-4d52-873a-fbb16dc77212")]
        public partial class ComPruebaMaverickAppFolder : RepoGenBaseFolder
        {
            mobile1RepositoryFolders.FragmentTwoFolder _fragmenttwo;
            RepoItemInfo _commonviewactivityInfo;

            /// <summary>
            /// Creates a new ComPruebaMaverick  folder.
            /// </summary>
            public ComPruebaMaverickAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComPruebaMaverick", "/mobileapp[@title='com.prueba.maverick']", parentFolder, 30000, null, false, "859bd624-5d3a-4d52-873a-fbb16dc77212", "")
            {
                _fragmenttwo = new mobile1RepositoryFolders.FragmentTwoFolder(this);
                _commonviewactivityInfo = new RepoItemInfo(this, "CommonViewActivity", "form[@title='CommonViewActivity']", 30000, null, "065f457c-532b-45d4-a9d8-dd01bde99f5b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("859bd624-5d3a-4d52-873a-fbb16dc77212")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("859bd624-5d3a-4d52-873a-fbb16dc77212")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CommonViewActivity item.
            /// </summary>
            [RepositoryItem("065f457c-532b-45d4-a9d8-dd01bde99f5b")]
            public virtual Ranorex.Form CommonViewActivity
            {
                get
                {
                    return _commonviewactivityInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The CommonViewActivity item info.
            /// </summary>
            [RepositoryItemInfo("065f457c-532b-45d4-a9d8-dd01bde99f5b")]
            public virtual RepoItemInfo CommonViewActivityInfo
            {
                get
                {
                    return _commonviewactivityInfo;
                }
            }

            /// <summary>
            /// The FragmentTwo folder.
            /// </summary>
            [RepositoryFolder("c78d26b8-bd1d-47e3-8eff-9a5e9a6f3a4d")]
            public virtual mobile1RepositoryFolders.FragmentTwoFolder FragmentTwo
            {
                get { return _fragmenttwo; }
            }
        }

        /// <summary>
        /// The FragmentTwoFolder folder.
        /// </summary>
        [RepositoryFolder("c78d26b8-bd1d-47e3-8eff-9a5e9a6f3a4d")]
        public partial class FragmentTwoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnrecInfo;
            RepoItemInfo _btnsaveInfo;
            RepoItemInfo _edittitleInfo;

            /// <summary>
            /// Creates a new FragmentTwo  folder.
            /// </summary>
            public FragmentTwoFolder(RepoGenBaseFolder parentFolder) :
                    base("FragmentTwo", "form[@title='CommonViewActivity']//container[@rid='fragmentTwo']", parentFolder, 30000, null, false, "c78d26b8-bd1d-47e3-8eff-9a5e9a6f3a4d", "")
            {
                _btnrecInfo = new RepoItemInfo(this, "BtnRec", "button[@rid='Btn_Rec']", 30000, null, "7ef88dd9-ca19-442a-9e19-92270015cfd1");
                _btnsaveInfo = new RepoItemInfo(this, "BtnSave", "container[@rid='relativeLayout1']/button[@rid='Btn_Save']", 30000, null, "6d22142a-6066-4312-8510-9ce4aaff08d1");
                _edittitleInfo = new RepoItemInfo(this, "EditTitle", "text[@rid='editTitle']", 30000, null, "a9ebfd4f-bcf2-4f79-a260-fbcd6ccec8ff");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c78d26b8-bd1d-47e3-8eff-9a5e9a6f3a4d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c78d26b8-bd1d-47e3-8eff-9a5e9a6f3a4d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnRec item.
            /// </summary>
            [RepositoryItem("7ef88dd9-ca19-442a-9e19-92270015cfd1")]
            public virtual Ranorex.Button BtnRec
            {
                get
                {
                    return _btnrecInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnRec item info.
            /// </summary>
            [RepositoryItemInfo("7ef88dd9-ca19-442a-9e19-92270015cfd1")]
            public virtual RepoItemInfo BtnRecInfo
            {
                get
                {
                    return _btnrecInfo;
                }
            }

            /// <summary>
            /// The BtnSave item.
            /// </summary>
            [RepositoryItem("6d22142a-6066-4312-8510-9ce4aaff08d1")]
            public virtual Ranorex.Button BtnSave
            {
                get
                {
                    return _btnsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSave item info.
            /// </summary>
            [RepositoryItemInfo("6d22142a-6066-4312-8510-9ce4aaff08d1")]
            public virtual RepoItemInfo BtnSaveInfo
            {
                get
                {
                    return _btnsaveInfo;
                }
            }

            /// <summary>
            /// The EditTitle item.
            /// </summary>
            [RepositoryItem("a9ebfd4f-bcf2-4f79-a260-fbcd6ccec8ff")]
            public virtual Ranorex.Text EditTitle
            {
                get
                {
                    return _edittitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EditTitle item info.
            /// </summary>
            [RepositoryItemInfo("a9ebfd4f-bcf2-4f79-a260-fbcd6ccec8ff")]
            public virtual RepoItemInfo EditTitleInfo
            {
                get
                {
                    return _edittitleInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}