///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace mobile1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Ranorexweb recording.
    /// </summary>
    [TestModule("3547bee5-6810-4b28-b155-f139ed4cd095", ModuleType.Recording, 1)]
    public partial class Ranorexweb : ITestModule
    {
        /// <summary>
        /// Holds an instance of the mobile1Repository repository.
        /// </summary>
        public static mobile1Repository repo = mobile1Repository.Instance;

        static Ranorexweb instance = new Ranorexweb();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Ranorexweb()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Ranorexweb Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'ranorex.RxBrowser' on device 'USB-300449f0b6253200'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("USB-300449f0b6253200", "ranorex.RxBrowser", true);
            Delay.Milliseconds(3500);
            
            // Browse to site.
            Report.Log(ReportLevel.Info, "Set Value", "Browse to site.\r\nSetting attribute PageUrl to 'https://tigers.dubber.net/login' on item 'Browser.Dom'.", repo.Browser.Dom.SelfInfo, new RecordItemIndex(1));
            repo.Browser.Dom.Self.Element.SetAttributeValue("PageUrl", "https://tigers.dubber.net/login");
            Delay.Milliseconds(10000);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'Browser.EtUrl' at 56;25", repo.Browser.EtUrlInfo, new RecordItemIndex(2));
            repo.Browser.EtUrl.Touch("56;25");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'google.com' on item 'Browser.EtUrl'.", repo.Browser.EtUrlInfo, new RecordItemIndex(3));
            repo.Browser.EtUrl.Element.SetAttributeValue("Text", "google.com");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{ENTER}' press on 'Browser.RxBrowserActivity'.", repo.Browser.RxBrowserActivityInfo, new RecordItemIndex(4));
            repo.Browser.RxBrowserActivity.PressKeys("{ENTER}");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
