///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace mobile1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RecordingModule recording.
    /// </summary>
    [TestModule("fcb10b0e-b1ab-48f1-bd6f-4e0b8831c581", ModuleType.Recording, 1)]
    public partial class RecordingModule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the mobile1Repository repository.
        /// </summary>
        public static mobile1Repository repo = mobile1Repository.Instance;

        static RecordingModule instance = new RecordingModule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RecordingModule()
        {
            NewVariable = "newrecording1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RecordingModule Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("77513ebc-5ce5-452b-9175-bc4b8ecf6b5e")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.prueba.maverick' on device 'USB-300449f0b6253200'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("USB-300449f0b6253200", "com.prueba.maverick", true);
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{DEL}' press on 'ComPruebaMaverick.CommonViewActivity'.", repo.ComPruebaMaverick.CommonViewActivityInfo, new RecordItemIndex(1));
            repo.ComPruebaMaverick.CommonViewActivity.PressKeys("{DEL}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Recordi' on item 'ComPruebaMaverick.FragmentTwo.EditTitle'.", repo.ComPruebaMaverick.FragmentTwo.EditTitleInfo, new RecordItemIndex(2));
            repo.ComPruebaMaverick.FragmentTwo.EditTitle.Element.SetAttributeValue("Text", "Recordi");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{DEL}' press on 'ComPruebaMaverick.CommonViewActivity'.", repo.ComPruebaMaverick.CommonViewActivityInfo, new RecordItemIndex(3));
            repo.ComPruebaMaverick.CommonViewActivity.PressKeys("{DEL}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Record' on item 'ComPruebaMaverick.FragmentTwo.EditTitle'.", repo.ComPruebaMaverick.FragmentTwo.EditTitleInfo, new RecordItemIndex(4));
            repo.ComPruebaMaverick.FragmentTwo.EditTitle.Element.SetAttributeValue("Text", "Record");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{DEL}' press on 'ComPruebaMaverick.CommonViewActivity'.", repo.ComPruebaMaverick.CommonViewActivityInfo, new RecordItemIndex(5));
            repo.ComPruebaMaverick.CommonViewActivity.PressKeys("{DEL}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Reco' on item 'ComPruebaMaverick.FragmentTwo.EditTitle'.", repo.ComPruebaMaverick.FragmentTwo.EditTitleInfo, new RecordItemIndex(6));
            repo.ComPruebaMaverick.FragmentTwo.EditTitle.Element.SetAttributeValue("Text", "Reco");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{DEL}' press on 'ComPruebaMaverick.CommonViewActivity'.", repo.ComPruebaMaverick.CommonViewActivityInfo, new RecordItemIndex(7));
            repo.ComPruebaMaverick.CommonViewActivity.PressKeys("{DEL}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Re' on item 'ComPruebaMaverick.FragmentTwo.EditTitle'.", repo.ComPruebaMaverick.FragmentTwo.EditTitleInfo, new RecordItemIndex(8));
            repo.ComPruebaMaverick.FragmentTwo.EditTitle.Element.SetAttributeValue("Text", "Re");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{DEL}' press on 'ComPruebaMaverick.CommonViewActivity'.", repo.ComPruebaMaverick.CommonViewActivityInfo, new RecordItemIndex(9));
            repo.ComPruebaMaverick.CommonViewActivity.PressKeys("{DEL}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'R' on item 'ComPruebaMaverick.FragmentTwo.EditTitle'.", repo.ComPruebaMaverick.FragmentTwo.EditTitleInfo, new RecordItemIndex(10));
            repo.ComPruebaMaverick.FragmentTwo.EditTitle.Element.SetAttributeValue("Text", "R");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{DEL}' press on 'ComPruebaMaverick.CommonViewActivity'.", repo.ComPruebaMaverick.CommonViewActivityInfo, new RecordItemIndex(11));
            repo.ComPruebaMaverick.CommonViewActivity.PressKeys("{DEL}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'newrecording1' on item 'ComPruebaMaverick.FragmentTwo.EditTitle'.", repo.ComPruebaMaverick.FragmentTwo.EditTitleInfo, new RecordItemIndex(12));
            repo.ComPruebaMaverick.FragmentTwo.EditTitle.Element.SetAttributeValue("Text", "newrecording1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{ENTER}' press on 'ComPruebaMaverick.CommonViewActivity'.", repo.ComPruebaMaverick.CommonViewActivityInfo, new RecordItemIndex(13));
            repo.ComPruebaMaverick.CommonViewActivity.PressKeys("{ENTER}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPruebaMaverick.FragmentTwo.BtnRec' at 160;146", repo.ComPruebaMaverick.FragmentTwo.BtnRecInfo, new RecordItemIndex(14));
            repo.ComPruebaMaverick.FragmentTwo.BtnRec.Touch("160;146");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPruebaMaverick.FragmentTwo.BtnRec' at 186;137", repo.ComPruebaMaverick.FragmentTwo.BtnRecInfo, new RecordItemIndex(15));
            repo.ComPruebaMaverick.FragmentTwo.BtnRec.Touch("186;137");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComPruebaMaverick.FragmentTwo.BtnSave' at 57;60", repo.ComPruebaMaverick.FragmentTwo.BtnSaveInfo, new RecordItemIndex(16));
            repo.ComPruebaMaverick.FragmentTwo.BtnSave.Touch("57;60");
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
