///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace trailTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the trailTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("2c3bd14e-d0c1-46f2-932f-48df6e1fb514")]
    public partial class trailTestRepository : RepoGenBaseFolder
    {
        static trailTestRepository instance = new trailTestRepository();
        trailTestRepositoryFolders.DubberAppFolder _dubber;

        /// <summary>
        /// Gets the singleton class instance representing the trailTestRepository element repository.
        /// </summary>
        [RepositoryFolder("2c3bd14e-d0c1-46f2-932f-48df6e1fb514")]
        public static trailTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public trailTestRepository() 
            : base("trailTestRepository", "/", null, 0, false, "2c3bd14e-d0c1-46f2-932f-48df6e1fb514", ".\\RepositoryImages\\trailTestRepository2c3bd14e.rximgres")
        {
            _dubber = new trailTestRepositoryFolders.DubberAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2c3bd14e-d0c1-46f2-932f-48df6e1fb514")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Dubber folder.
        /// </summary>
        [RepositoryFolder("c360ccc2-36a2-4d90-99d6-ba6cea38d7d8")]
        public virtual trailTestRepositoryFolders.DubberAppFolder Dubber
        {
            get { return _dubber; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class trailTestRepositoryFolders
    {
        /// <summary>
        /// The DubberAppFolder folder.
        /// </summary>
        [RepositoryFolder("c360ccc2-36a2-4d90-99d6-ba6cea38d7d8")]
        public partial class DubberAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _useremailInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _managedapsbuttonInfo;
            RepoItemInfo _accounttabInfo;
            RepoItemInfo _iconcogiconwhiteInfo;
            RepoItemInfo _dropdownlogoutInfo;

            /// <summary>
            /// Creates a new Dubber  folder.
            /// </summary>
            public DubberAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dubber", "/dom[12]", parentFolder, 30000, null, false, "c360ccc2-36a2-4d90-99d6-ba6cea38d7d8", "")
            {
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "12b930ea-d019-4865-a804-4f506d96e6a1");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//input[#'submit_button']", 30000, null, "c80c42e7-9d74-4644-a989-f419966de9a6");
                _managedapsbuttonInfo = new RepoItemInfo(this, "ManageDapsButton", ".//a[#'manage_daps_button']", 30000, null, "9fe96711-c5e9-474d-af56-1982888130cd");
                _accounttabInfo = new RepoItemInfo(this, "AccountTab", ".//a[#'account_tab']", 30000, null, "eedac8a0-3c78-4a8a-8ff4-b2be193825fc");
                _iconcogiconwhiteInfo = new RepoItemInfo(this, "IconCogIconWhite", ".//a[#'profile-ddt']/i", 30000, null, "79935480-f753-45e3-be9f-84290f86e6db");
                _dropdownlogoutInfo = new RepoItemInfo(this, "DropDownLogout", ".//a[#'drop_down_logout']", 30000, null, "170b2c2d-12f7-49ab-9f8c-6281e3c737fb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c360ccc2-36a2-4d90-99d6-ba6cea38d7d8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c360ccc2-36a2-4d90-99d6-ba6cea38d7d8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("12b930ea-d019-4865-a804-4f506d96e6a1")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("12b930ea-d019-4865-a804-4f506d96e6a1")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("c80c42e7-9d74-4644-a989-f419966de9a6")]
            public virtual Ranorex.InputTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("c80c42e7-9d74-4644-a989-f419966de9a6")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The ManageDapsButton item.
            /// </summary>
            [RepositoryItem("9fe96711-c5e9-474d-af56-1982888130cd")]
            public virtual Ranorex.ATag ManageDapsButton
            {
                get
                {
                    return _managedapsbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ManageDapsButton item info.
            /// </summary>
            [RepositoryItemInfo("9fe96711-c5e9-474d-af56-1982888130cd")]
            public virtual RepoItemInfo ManageDapsButtonInfo
            {
                get
                {
                    return _managedapsbuttonInfo;
                }
            }

            /// <summary>
            /// The AccountTab item.
            /// </summary>
            [RepositoryItem("eedac8a0-3c78-4a8a-8ff4-b2be193825fc")]
            public virtual Ranorex.ATag AccountTab
            {
                get
                {
                    return _accounttabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AccountTab item info.
            /// </summary>
            [RepositoryItemInfo("eedac8a0-3c78-4a8a-8ff4-b2be193825fc")]
            public virtual RepoItemInfo AccountTabInfo
            {
                get
                {
                    return _accounttabInfo;
                }
            }

            /// <summary>
            /// The IconCogIconWhite item.
            /// </summary>
            [RepositoryItem("79935480-f753-45e3-be9f-84290f86e6db")]
            public virtual Ranorex.ITag IconCogIconWhite
            {
                get
                {
                    return _iconcogiconwhiteInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The IconCogIconWhite item info.
            /// </summary>
            [RepositoryItemInfo("79935480-f753-45e3-be9f-84290f86e6db")]
            public virtual RepoItemInfo IconCogIconWhiteInfo
            {
                get
                {
                    return _iconcogiconwhiteInfo;
                }
            }

            /// <summary>
            /// The DropDownLogout item.
            /// </summary>
            [RepositoryItem("170b2c2d-12f7-49ab-9f8c-6281e3c737fb")]
            public virtual Ranorex.ATag DropDownLogout
            {
                get
                {
                    return _dropdownlogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DropDownLogout item info.
            /// </summary>
            [RepositoryItemInfo("170b2c2d-12f7-49ab-9f8c-6281e3c737fb")]
            public virtual RepoItemInfo DropDownLogoutInfo
            {
                get
                {
                    return _dropdownlogoutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}